### ISSUE TITLE
Rule `hositAwait` produces invalid code with `XCTAssertThrowsError()`

### ISSUE THREAD

**Issue by jessesquires** [nicklockwood/SwiftFormat#1478]
Release: `0.51.12`

Given the following code:

```swift
await XCTAssertThrowsError(try await thing.doSomething())
```

SwiftFormat will produce:

```swift
await XCTAssertThrowsError(try thing.doSomething())
```

Xcode produces an error at `thing.doSomething()`:

```
Expression is 'async' but is not marked with 'await'
```

**Comment by MKW11** [comment]
Thank you, @jessesquires. I was going to raise a similar issue today.  It's not only the `XCTAssertThrowsError()` that has the problem; in fact, it's happening for the `async` auto closures used as a parameter. For example, if there was a method with a signature: 

``` swift 
func doSomething(_ asyncExpression: @autoclosure () async throws -> some Sendable) async throws
```

for the following call
``` swift 
await doSomething(try await doSomeAsync())
```

SwiftFomat would produce:
``` swift 
await doSomething(try doSomeAsync())
```

**Comment by jessesquires** [comment]
@MKW11 thanks! I updated the title.

**Comment by nicklockwood** [comment]
@jessesquires does this code actually compile?

```swift
await XCTAssertThrowsError(try await thing.doSomething())
```

My understanding is that the `XCTAssertThrowsError()` autoclosure is not async. I tried on Xcode 15 beta and that doesn't seem to have changed?

**Comment by nicklockwood** [comment]
@MKW11 did you add `--asynccapturing doSomething` to your SwiftFormat options? SwiftFormat isn't currently capable of detecting @autoclosure arguments automatically, so you have to tell it about any functions that use them.

**Comment by jessesquires** [comment]
@nicklockwood 

> does this code actually compile?

Oh. Ha! Wow, so I just realized the codebase I'm working on **redefines** `XCTAssertThrowsError()` with an async autoclosure. 🤦🏼‍♂️ 🤦🏼‍♂️ 🤦🏼‍♂️ 🤦🏼‍♂️ 

Very sorry for not realizing that sooner and causing some confusion.

In any case, I think @MKW11 has provided the generalized failure case.

**Comment by nicklockwood** [comment]
@jessesquires so then probably the fix in your case is to add `--asynccapturing XCTAssertThrowsError`

**Comment by nicklockwood** [comment]
OK, I can't see anything here that isn't already a known issue covered by the `--asynccapturing` and `--throwcapturing` options, but let me know if you find something that can't be solved with those.

**Comment by AndriiPetrovDev** [comment]
I want to add my case

**Comment by bbrk24** [comment]
This can also happen with just `try` and no await -- SwiftFormat removes the second `try` from this:

```swift
/// Try to cast the object to the given type, and throw if it fails (`as?` + `XCTUnwrap`).
func XCTCast<TSource, TTarget>(
    _ expression: @autoclosure () throws -> TSource,
    _: TTarget.Type = TTarget.self,
    _ message: String = "",
    file: StaticString = #file,
    line: UInt = #line
) throws -> TTarget {
    try XCTUnwrap(try expression() as? TTarget, message, file: file, line: line)
}
```

**Comment by nicklockwood** [comment]
@bbrk hmm, that's a bug. XCTUnwrap should be on the default exclusion list for try hoisting, but I must have forgotten to include it.

**Comment by FelixLisczyk** [comment]
Any updates on this issue? I can still reproduce it with the current version 0.58.1.

**Comment by lhunath** [comment]
```diff
         if await UNUserNotificationCenter.current().pendingNotificationRequests().contains(request) |||
-            (await UNUserNotificationCenter.current().deliveredNotifications().map(\.request).contains(request)) {
+            (UNUserNotificationCenter.current().deliveredNotifications().map(\.request).contains(request)) {
             return request.identifier
         }
```
await is removed despite `--asynccapturing |||`
<details>
<summary><code>public func ||| (lhs: Bool, rhs: @autoclosure () async throws -> Bool) async rethrows -> Bool</code></summary>
<pre>
infix operator |||: NilCoalescingPrecedence
public func ||| (lhs: Bool, rhs: @autoclosure () async throws -> Bool) async rethrows -> Bool {
    if lhs {
        return true
    }
    return try await rhs()
}
</pre>
</details>
